// Generated by gencpp from file pub_sub/number.msg
// DO NOT EDIT!


#ifndef PUB_SUB_MESSAGE_NUMBER_H
#define PUB_SUB_MESSAGE_NUMBER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pub_sub
{
template <class ContainerAllocator>
struct number_
{
  typedef number_<ContainerAllocator> Type;

  number_()
    : number(0.0)  {
    }
  number_(const ContainerAllocator& _alloc)
    : number(0.0)  {
  (void)_alloc;
    }



   typedef double _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::pub_sub::number_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pub_sub::number_<ContainerAllocator> const> ConstPtr;

}; // struct number_

typedef ::pub_sub::number_<std::allocator<void> > number;

typedef boost::shared_ptr< ::pub_sub::number > numberPtr;
typedef boost::shared_ptr< ::pub_sub::number const> numberConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pub_sub::number_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pub_sub::number_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pub_sub::number_<ContainerAllocator1> & lhs, const ::pub_sub::number_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pub_sub::number_<ContainerAllocator1> & lhs, const ::pub_sub::number_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pub_sub

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pub_sub::number_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pub_sub::number_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pub_sub::number_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pub_sub::number_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pub_sub::number_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pub_sub::number_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pub_sub::number_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4dcebbc33e65171f948c63edad2d5dae";
  }

  static const char* value(const ::pub_sub::number_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4dcebbc33e65171fULL;
  static const uint64_t static_value2 = 0x948c63edad2d5daeULL;
};

template<class ContainerAllocator>
struct DataType< ::pub_sub::number_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pub_sub/number";
  }

  static const char* value(const ::pub_sub::number_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pub_sub::number_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 number\n"
;
  }

  static const char* value(const ::pub_sub::number_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pub_sub::number_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct number_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pub_sub::number_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pub_sub::number_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<double>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUB_SUB_MESSAGE_NUMBER_H
