// Generated by gencpp from file week2test/NumberRequest.msg
// DO NOT EDIT!


#ifndef WEEK2TEST_MESSAGE_NUMBERREQUEST_H
#define WEEK2TEST_MESSAGE_NUMBERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace week2test
{
template <class ContainerAllocator>
struct NumberRequest_
{
  typedef NumberRequest_<ContainerAllocator> Type;

  NumberRequest_()
    : ask(0.0)  {
    }
  NumberRequest_(const ContainerAllocator& _alloc)
    : ask(0.0)  {
  (void)_alloc;
    }



   typedef double _ask_type;
  _ask_type ask;





  typedef boost::shared_ptr< ::week2test::NumberRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::week2test::NumberRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NumberRequest_

typedef ::week2test::NumberRequest_<std::allocator<void> > NumberRequest;

typedef boost::shared_ptr< ::week2test::NumberRequest > NumberRequestPtr;
typedef boost::shared_ptr< ::week2test::NumberRequest const> NumberRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::week2test::NumberRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::week2test::NumberRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::week2test::NumberRequest_<ContainerAllocator1> & lhs, const ::week2test::NumberRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ask == rhs.ask;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::week2test::NumberRequest_<ContainerAllocator1> & lhs, const ::week2test::NumberRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace week2test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::week2test::NumberRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::week2test::NumberRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::week2test::NumberRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::week2test::NumberRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::week2test::NumberRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::week2test::NumberRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::week2test::NumberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddbe15febb103006edb58c3b0b204bed";
  }

  static const char* value(const ::week2test::NumberRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xddbe15febb103006ULL;
  static const uint64_t static_value2 = 0xedb58c3b0b204bedULL;
};

template<class ContainerAllocator>
struct DataType< ::week2test::NumberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "week2test/NumberRequest";
  }

  static const char* value(const ::week2test::NumberRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::week2test::NumberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 ask\n"
;
  }

  static const char* value(const ::week2test::NumberRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::week2test::NumberRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ask);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NumberRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::week2test::NumberRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::week2test::NumberRequest_<ContainerAllocator>& v)
  {
    s << indent << "ask: ";
    Printer<double>::stream(s, indent + "  ", v.ask);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEEK2TEST_MESSAGE_NUMBERREQUEST_H
