// Generated by gencpp from file sub_cli/Number.msg
// DO NOT EDIT!


#ifndef SUB_CLI_MESSAGE_NUMBER_H
#define SUB_CLI_MESSAGE_NUMBER_H

#include <ros/service_traits.h>


#include <sub_cli/NumberRequest.h>
#include <sub_cli/NumberResponse.h>


namespace sub_cli
{

struct Number
{

typedef NumberRequest Request;
typedef NumberResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Number
} // namespace sub_cli


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sub_cli::Number > {
  static const char* value()
  {
    return "89ba4f2ce3e045af45888facdc421449";
  }

  static const char* value(const ::sub_cli::Number&) { return value(); }
};

template<>
struct DataType< ::sub_cli::Number > {
  static const char* value()
  {
    return "sub_cli/Number";
  }

  static const char* value(const ::sub_cli::Number&) { return value(); }
};


// service_traits::MD5Sum< ::sub_cli::NumberRequest> should match
// service_traits::MD5Sum< ::sub_cli::Number >
template<>
struct MD5Sum< ::sub_cli::NumberRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sub_cli::Number >::value();
  }
  static const char* value(const ::sub_cli::NumberRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sub_cli::NumberRequest> should match
// service_traits::DataType< ::sub_cli::Number >
template<>
struct DataType< ::sub_cli::NumberRequest>
{
  static const char* value()
  {
    return DataType< ::sub_cli::Number >::value();
  }
  static const char* value(const ::sub_cli::NumberRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sub_cli::NumberResponse> should match
// service_traits::MD5Sum< ::sub_cli::Number >
template<>
struct MD5Sum< ::sub_cli::NumberResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sub_cli::Number >::value();
  }
  static const char* value(const ::sub_cli::NumberResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sub_cli::NumberResponse> should match
// service_traits::DataType< ::sub_cli::Number >
template<>
struct DataType< ::sub_cli::NumberResponse>
{
  static const char* value()
  {
    return DataType< ::sub_cli::Number >::value();
  }
  static const char* value(const ::sub_cli::NumberResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUB_CLI_MESSAGE_NUMBER_H
