// Generated by gencpp from file sub_cli/NumberRequest.msg
// DO NOT EDIT!


#ifndef SUB_CLI_MESSAGE_NUMBERREQUEST_H
#define SUB_CLI_MESSAGE_NUMBERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sub_cli
{
template <class ContainerAllocator>
struct NumberRequest_
{
  typedef NumberRequest_<ContainerAllocator> Type;

  NumberRequest_()
    : number(0.0)  {
    }
  NumberRequest_(const ContainerAllocator& _alloc)
    : number(0.0)  {
  (void)_alloc;
    }



   typedef double _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::sub_cli::NumberRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sub_cli::NumberRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NumberRequest_

typedef ::sub_cli::NumberRequest_<std::allocator<void> > NumberRequest;

typedef boost::shared_ptr< ::sub_cli::NumberRequest > NumberRequestPtr;
typedef boost::shared_ptr< ::sub_cli::NumberRequest const> NumberRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sub_cli::NumberRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sub_cli::NumberRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sub_cli::NumberRequest_<ContainerAllocator1> & lhs, const ::sub_cli::NumberRequest_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sub_cli::NumberRequest_<ContainerAllocator1> & lhs, const ::sub_cli::NumberRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sub_cli

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sub_cli::NumberRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sub_cli::NumberRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sub_cli::NumberRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sub_cli::NumberRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sub_cli::NumberRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sub_cli::NumberRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sub_cli::NumberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4dcebbc33e65171f948c63edad2d5dae";
  }

  static const char* value(const ::sub_cli::NumberRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4dcebbc33e65171fULL;
  static const uint64_t static_value2 = 0x948c63edad2d5daeULL;
};

template<class ContainerAllocator>
struct DataType< ::sub_cli::NumberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sub_cli/NumberRequest";
  }

  static const char* value(const ::sub_cli::NumberRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sub_cli::NumberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 number\n"
;
  }

  static const char* value(const ::sub_cli::NumberRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sub_cli::NumberRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NumberRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sub_cli::NumberRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sub_cli::NumberRequest_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<double>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUB_CLI_MESSAGE_NUMBERREQUEST_H
