// Generated by gencpp from file ser_cli/NumberRequest.msg
// DO NOT EDIT!


#ifndef SER_CLI_MESSAGE_NUMBERREQUEST_H
#define SER_CLI_MESSAGE_NUMBERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ser_cli
{
template <class ContainerAllocator>
struct NumberRequest_
{
  typedef NumberRequest_<ContainerAllocator> Type;

  NumberRequest_()
    : random_Number(0.0)  {
    }
  NumberRequest_(const ContainerAllocator& _alloc)
    : random_Number(0.0)  {
  (void)_alloc;
    }



   typedef double _random_Number_type;
  _random_Number_type random_Number;





  typedef boost::shared_ptr< ::ser_cli::NumberRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ser_cli::NumberRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NumberRequest_

typedef ::ser_cli::NumberRequest_<std::allocator<void> > NumberRequest;

typedef boost::shared_ptr< ::ser_cli::NumberRequest > NumberRequestPtr;
typedef boost::shared_ptr< ::ser_cli::NumberRequest const> NumberRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ser_cli::NumberRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ser_cli::NumberRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ser_cli::NumberRequest_<ContainerAllocator1> & lhs, const ::ser_cli::NumberRequest_<ContainerAllocator2> & rhs)
{
  return lhs.random_Number == rhs.random_Number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ser_cli::NumberRequest_<ContainerAllocator1> & lhs, const ::ser_cli::NumberRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ser_cli

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ser_cli::NumberRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ser_cli::NumberRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ser_cli::NumberRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ser_cli::NumberRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ser_cli::NumberRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ser_cli::NumberRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ser_cli::NumberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "624326930e08fe90db11591c270aef20";
  }

  static const char* value(const ::ser_cli::NumberRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x624326930e08fe90ULL;
  static const uint64_t static_value2 = 0xdb11591c270aef20ULL;
};

template<class ContainerAllocator>
struct DataType< ::ser_cli::NumberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ser_cli/NumberRequest";
  }

  static const char* value(const ::ser_cli::NumberRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ser_cli::NumberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 random_Number\n"
;
  }

  static const char* value(const ::ser_cli::NumberRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ser_cli::NumberRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.random_Number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NumberRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ser_cli::NumberRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ser_cli::NumberRequest_<ContainerAllocator>& v)
  {
    s << indent << "random_Number: ";
    Printer<double>::stream(s, indent + "  ", v.random_Number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SER_CLI_MESSAGE_NUMBERREQUEST_H
