// Generated by gencpp from file ser_cli/NumberResponse.msg
// DO NOT EDIT!


#ifndef SER_CLI_MESSAGE_NUMBERRESPONSE_H
#define SER_CLI_MESSAGE_NUMBERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ser_cli
{
template <class ContainerAllocator>
struct NumberResponse_
{
  typedef NumberResponse_<ContainerAllocator> Type;

  NumberResponse_()
    : answer(false)  {
    }
  NumberResponse_(const ContainerAllocator& _alloc)
    : answer(false)  {
  (void)_alloc;
    }



   typedef uint8_t _answer_type;
  _answer_type answer;





  typedef boost::shared_ptr< ::ser_cli::NumberResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ser_cli::NumberResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NumberResponse_

typedef ::ser_cli::NumberResponse_<std::allocator<void> > NumberResponse;

typedef boost::shared_ptr< ::ser_cli::NumberResponse > NumberResponsePtr;
typedef boost::shared_ptr< ::ser_cli::NumberResponse const> NumberResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ser_cli::NumberResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ser_cli::NumberResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ser_cli::NumberResponse_<ContainerAllocator1> & lhs, const ::ser_cli::NumberResponse_<ContainerAllocator2> & rhs)
{
  return lhs.answer == rhs.answer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ser_cli::NumberResponse_<ContainerAllocator1> & lhs, const ::ser_cli::NumberResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ser_cli

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ser_cli::NumberResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ser_cli::NumberResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ser_cli::NumberResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ser_cli::NumberResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ser_cli::NumberResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ser_cli::NumberResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ser_cli::NumberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00a50c1bd863054691f197c515f4e922";
  }

  static const char* value(const ::ser_cli::NumberResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00a50c1bd8630546ULL;
  static const uint64_t static_value2 = 0x91f197c515f4e922ULL;
};

template<class ContainerAllocator>
struct DataType< ::ser_cli::NumberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ser_cli/NumberResponse";
  }

  static const char* value(const ::ser_cli::NumberResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ser_cli::NumberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool answer\n"
"\n"
;
  }

  static const char* value(const ::ser_cli::NumberResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ser_cli::NumberResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.answer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NumberResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ser_cli::NumberResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ser_cli::NumberResponse_<ContainerAllocator>& v)
  {
    s << indent << "answer: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.answer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SER_CLI_MESSAGE_NUMBERRESPONSE_H
