// Generated by gencpp from file ser_cli/Number.msg
// DO NOT EDIT!


#ifndef SER_CLI_MESSAGE_NUMBER_H
#define SER_CLI_MESSAGE_NUMBER_H

#include <ros/service_traits.h>


#include <ser_cli/NumberRequest.h>
#include <ser_cli/NumberResponse.h>


namespace ser_cli
{

struct Number
{

typedef NumberRequest Request;
typedef NumberResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Number
} // namespace ser_cli


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ser_cli::Number > {
  static const char* value()
  {
    return "afa02421f803f6ba8635e0239ef71de9";
  }

  static const char* value(const ::ser_cli::Number&) { return value(); }
};

template<>
struct DataType< ::ser_cli::Number > {
  static const char* value()
  {
    return "ser_cli/Number";
  }

  static const char* value(const ::ser_cli::Number&) { return value(); }
};


// service_traits::MD5Sum< ::ser_cli::NumberRequest> should match
// service_traits::MD5Sum< ::ser_cli::Number >
template<>
struct MD5Sum< ::ser_cli::NumberRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ser_cli::Number >::value();
  }
  static const char* value(const ::ser_cli::NumberRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ser_cli::NumberRequest> should match
// service_traits::DataType< ::ser_cli::Number >
template<>
struct DataType< ::ser_cli::NumberRequest>
{
  static const char* value()
  {
    return DataType< ::ser_cli::Number >::value();
  }
  static const char* value(const ::ser_cli::NumberRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ser_cli::NumberResponse> should match
// service_traits::MD5Sum< ::ser_cli::Number >
template<>
struct MD5Sum< ::ser_cli::NumberResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ser_cli::Number >::value();
  }
  static const char* value(const ::ser_cli::NumberResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ser_cli::NumberResponse> should match
// service_traits::DataType< ::ser_cli::Number >
template<>
struct DataType< ::ser_cli::NumberResponse>
{
  static const char* value()
  {
    return DataType< ::ser_cli::Number >::value();
  }
  static const char* value(const ::ser_cli::NumberResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SER_CLI_MESSAGE_NUMBER_H
