// Generated by gencpp from file little_car/Car.msg
// DO NOT EDIT!


#ifndef LITTLE_CAR_MESSAGE_CAR_H
#define LITTLE_CAR_MESSAGE_CAR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace little_car
{
template <class ContainerAllocator>
struct Car_
{
  typedef Car_<ContainerAllocator> Type;

  Car_()
    : x(0)
    , y(0)
    , yaw(0.0)  {
    }
  Car_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _x_type;
  _x_type x;

   typedef uint8_t _y_type;
  _y_type y;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::little_car::Car_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::little_car::Car_<ContainerAllocator> const> ConstPtr;

}; // struct Car_

typedef ::little_car::Car_<std::allocator<void> > Car;

typedef boost::shared_ptr< ::little_car::Car > CarPtr;
typedef boost::shared_ptr< ::little_car::Car const> CarConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::little_car::Car_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::little_car::Car_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::little_car::Car_<ContainerAllocator1> & lhs, const ::little_car::Car_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::little_car::Car_<ContainerAllocator1> & lhs, const ::little_car::Car_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace little_car

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::little_car::Car_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::little_car::Car_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::little_car::Car_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::little_car::Car_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::little_car::Car_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::little_car::Car_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::little_car::Car_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd68a8a366b933ecec7067b122a8e02d";
  }

  static const char* value(const ::little_car::Car_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd68a8a366b933ecULL;
  static const uint64_t static_value2 = 0xec7067b122a8e02dULL;
};

template<class ContainerAllocator>
struct DataType< ::little_car::Car_<ContainerAllocator> >
{
  static const char* value()
  {
    return "little_car/Car";
  }

  static const char* value(const ::little_car::Car_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::little_car::Car_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 x\n"
"uint8 y\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::little_car::Car_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::little_car::Car_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Car_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::little_car::Car_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::little_car::Car_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LITTLE_CAR_MESSAGE_CAR_H
